# Generated by Django 4.2.2 on 2023-06-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayboxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mobile_network', models.CharField(choices=[('Mtn', 'MTN'), ('Vodafone', 'Vodafone'), ('AirtelTigo', 'AirtelTigo')], max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('bank_account', models.CharField(max_length=50)),
            ],
        ),
    ]
