# Generated by Django 4.2.2 on 2023-06-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_payboxtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payboxtransaction',
            name='bank_code',
            field=models.CharField(choices=[('00110', 'Absa Bank'), ('00220', 'Bank B'), ('00330', 'Bank C')], default='00110', max_length=10),
        ),
        migrations.AddField(
            model_name='payboxtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], default='Deposit', max_length=20),
        ),
        migrations.AlterField(
            model_name='payboxtransaction',
            name='mobile_network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('Vodafone', 'Vodafone'), ('AirtelTigo', 'AirtelTigo')], max_length=20),
        ),
    ]
