# Generated by Django 4.2.2 on 2023-06-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_payboxtransaction_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payboxtransaction',
            name='bank_code',
            field=models.CharField(choices=[('00110', 'Absa Bank'), ('00220', 'Ecobanks'), ('00330', 'Access Bank')], default='00110', max_length=10),
        ),
    ]
