# Generated by Django 4.2.2 on 2023-06-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_payboxtransaction_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payboxtransaction',
            name='callback_url',
            field=models.URLField(blank=True),
        ),
    ]
