# Generated by Django 4.2.2 on 2023-06-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_payboxtransaction_callback_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('recipient_account_number', models.CharField(max_length=20)),
                ('recipient_bank_code', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='PayboxTransaction',
        ),
    ]
