# Generated by Django 4.2.2 on 2023-06-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_billpayment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='reference',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
