# Generated by Django 4.2.2 on 2023-06-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_billpayment_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billpayment',
            old_name='reference',
            new_name='ref',
        ),
    ]
